### ISSUE TITLE
Bump version number

### ISSUE THREAD

**Issue by pft** [andyetitmoves/libmpdee#9]
Can the version number be updated, so that dependent libs can reference the new number. E.g. if mingus re-installs via melpa, and the user has a cached version of libmpdee, emacs will not download a new version (needed for emacs28 and beyond).

line 7 of libmpdee.el:
```
;; Version:     2.1
```

**Comment by andyetitmoves** [comment]
Done

https://github.com/andyetitmoves/libmpdee/commit/9a84e074385cd085622f94e720a968a0e05ceae5
